kind: pipeline
type: ssh
name: default
server:
  host:
    from_secret: org_host
  user: g2
  ssh_key:
    from_secret: org_key
  port: 2475
steps:
  - name: pre-checks
    commands:
      - pwd
      - whoami
      - ls
  - name: compile
    commands:
      - rust.fix
      - cargo build --release
  - name: rust test
    commands:
      - cargo test --release
  - name: test xxtea-cli
    commands:
      - ./test.py xxtea-cli
